language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t strickert/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true strickert/docker-react npm run test